### ISSUE TITLE
Inject bean in a plugin MyBatis has a null value

### ISSUE THREAD

**Issue by gallegote** [mybatis/cdi#13]
Hi

I am using CDI (Weld ) in a web application developed in JSF and MyBatis on a Tomcat application server.

When I inject a bean into a plugin of MyBatis, the injected bean always has a null value, instead of injecting the correct instance of the bean.

What am I doing wrong?

Regards 

```
import es.metadata.metaqualitas.web.SessionBean;
import java.io.Serializable;
import java.util.Properties;
import javax.inject.Inject;
import javax.inject.Named;
import org.apache.ibatis.executor.Executor;
import org.apache.ibatis.mapping.MappedStatement;
import org.apache.ibatis.plugin.Interceptor;
import org.apache.ibatis.plugin.Intercepts;
import org.apache.ibatis.plugin.Invocation;
import org.apache.ibatis.plugin.Plugin;
import org.apache.ibatis.plugin.Signature;
import org.apache.ibatis.session.ResultHandler;
import org.apache.ibatis.session.RowBounds;
import org.apache.log4j.Logger;

@Intercepts({
    @Signature(type = Executor.class, method = "query", args = {MappedStatement.class, Object.class, RowBounds.class, ResultHandler.class}),
    @Signature(type = Executor.class, method = "update", args = {MappedStatement.class, Object.class})
})
public class ExamplePlugin implements Interceptor, Serializable {

    //log has a ApplicationScope
    @Inject
    private Logger log;

    //sessionBean has a SessionScoped        
    @Inject
    private SessionBean sessionBean;

    @Override
    public Object intercept(Invocation invocation) throws Throwable {
        //log and sessionBean are always worth null and launch NullPointerException
        log.info(sessionBean.getUsuario());        
        return invocation.proceed();
    }

    @Override
    public Object plugin(Object target) {
        return Plugin.wrap(target, this);
    }

    @Override
    public void setProperties(Properties properties) {    
    }
}
```

```
import javax.enterprise.inject.Produces;
import javax.enterprise.inject.spi.InjectionPoint;
import javax.inject.Inject;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

@ApplicationScoped
@Named
public class LoggerProducer {

    @Produces  
    public Logger produceLogger(InjectionPoint injectionPoint) {        
        return Logger.getLogger(injectionPoint.getMember().getDeclaringClass().getName());  
    }
}
```

```

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class SessionBean implements Serializable {

    private String usuario;

    public String getUsuario(){
        return usuario;
    }

    public void setUsuario(String usuario){
        this.usuario = usuario;
    }

    @PostConstruct
    public void init() {
        usuario = "Pedro";
    }
}
```

**Comment by hazendaz** [comment]
I'm not familiar with the interceptor in mybatis but I am with CDI.  How is your interceptor instantiated?  If it is newed at any point in time after tomcat is up and running, it won't play with CDI thus your null issues.  You can resolve that pretty easily though by adding Deltaspike and performing BeanProvider.injectFields(this);  Toss that on the intercept method and it will get that going for you so long as the interceptor itself isn't expected to be application scoped as that wouldn't jive right (ie Session can have application scoped but Applicaiton scoped cannot have session scoped otherwise it wouldn't be thread safe).  Additionally, if you do use deltaspike I would add @Vetoed to the class since that provides clear indication it doesn't play with CDI.  Otherwise, CDI would be creating a object for no reason that is never used.  Further, if the interceptor actually is part of some other object, it is best to label it with @Dependent.  Newer CDI/WELD versions require some sort of annotation to work as they are getting more strict.  I am guessing that isn't the case here but wanted to point it out.

For reference...I'm running tomcat stacks with CDI/Weld 2.2.8, Jersey 2.6, Metro 2.3.1, Jackson 2.5.0, JSF 2.1.29, Richfaces 4.3.7, Omnifaces 1.10, Quartz 2.2.1, Mybatis 3.2.8, EhCache 2.9.0, Deltaspike 1.2.1, etc.  There is a mybatis library now for CDI but we wrote our own internal one way before that existed to inject the sql session factories.  This is all in production for a long time now.  Things do start getting tricking going forwards expecially with CDI post 2.2.4 when the window id's are introduced.  All that said, I think it is possible to get what you are after working.

**Comment by gallegote** [comment]
The instance of the interceptor not built for me. The interceptor instance is created by mybatis from a configuration file. Now I understand why I do not properly injected beans.

I have tried using Deltaspike and almost works. By injecting a bean with applicationScope it works, but to inject a sessionScope fails, instead of injecting my SessionBean, try to create a new session bean each time it is used the interceptor. I guess you do not know cdi SessionBean injected.

Any ideas?

**Comment by hazendaz** [comment]
Yup...sounds like interceptor is application scoped.  You won't be able to inject session into there as that wouldn't be thread safe.  Appears you are just trying to log and not use interceptor for anything else.  I'd just put that in the dao which would be able to log user info for you.  That is unless you are trying to do something else.

**Comment by mnesarco** [comment]
This is not related to mybatis-cdi, please post this in mybatis3.
