### ISSUE TITLE
UnserializableDependencyException

### ISSUE THREAD

**Issue by raupachz** [mybatis/cdi#37]
Hello group,

I am trying to use MyBatis-CDI with a new JSF project. I have a `ViewScoped Bean` and want to inject a `Mapper`. 

This leads to the following exception during startup:
```
Caused by: org.jboss.weld.exceptions.UnserializableDependencyException: 
WELD-001413: The bean Managed Bean [class de.e2n.gastroapp.admin.Home] with qualifiers
[@Default @Named @Any] declares a passivating scope but has a non-passivation-capable
dependency org.mybatis.cdi.MyBatisBean@60872782
```

If I change the scope from ViewScope to RequestScoped it works. SessionScoped and ApplicationScoped yield the same exception.

Should I provide a [test case?](http://sscce.org/)

**Versions:**
Apache Tomcat 8.0.32
Mojarra 2.2.13
Weld 2.2.16.Final
MyBatis 3.3.1
MyBatis-CDI 1.0.0-beta3

**Comment by raupachz** [comment]
Ok, If I add `transient` to the reference it works. Is this the way it should be?

```
@Inject
@Mapper
private transient ExampleMapper mapper;
```

**Comment by hazendaz** [comment]
@raupachz Yes that is correct.  There is not really any good need to make the mapper serializable in any way.  Based on your description though, you might want to further decouple your view from your dao.  Personally I would create a separate dao that has the above mapper injected and uses it there.  Then that dao would be RequestScoped and would be injected where needed (and also marked transient).  Further decoupling could be achieved where you put the dao behind soap/rest calls.  If you look closely at the dao, it should be a little more clear that there is next to nothing gained by having the class serializable as it really shouldn't be holding any state information and that is where the mappers get consumed.  I suspect you might be after some sort of caching which works really well in this scenario.

My general setup...
Apache Tomcat 8.0.32
Mojarra 2.2.12 (I'm a little behind)
Mybatis 3.3.1
Mybatis-cdi 1.0.0.beta3
Mybatis-ehcache 1.0.3
Weld 2.3.1.Final

Let me know if you are otherwise all set on this or have any additional questions.  I'll leave this open until I hear back from you.  

Thanks

**Comment by raupachz** [comment]
@hazendaz Hi Jeremy, thanks for the detailed reply. Yes, I follow the same approach. In this case however I just had a view and needed some values out of the database. For simplicity I did not want to introduce another class just for the sole purpose of annotating it with `RequestScoped` and injecting the mapper.

So we can consider this closed. Thanks again!

**Comment by hazendaz** [comment]
Great!  Thanks for getting back with me.
