### ISSUE TITLE
Doesn't work with WebLogic 12c

### ISSUE THREAD

**Issue by artplastika** [mybatis/cdi#5]
Injection gives following error:

> There are no SqlSessionFactory producers properly configured.

Sample application to demonstrate problem is here: https://github.com/artplastika/mybatis-cdi-example/tree/weblogic
Maybe this will help, WebLogic (as well as WildFly) uses WELD as CDI implementation: http://weld.cdi-spec.org/

**Comment by hazendaz** [comment]
#11 is the same issue.  I suspect a few things so would look at that issue for what I wrote up.  Weld doesn't care about the extra beans.xml by the way.  It will spit out a warning but that is it.  It will also state it is using the one from the WAR rather than jar.  I'm guessing that is harder to just say the jar is wrong considering it could be used elsewhere where still needed.

**Comment by mnesarco** [comment]
Hi, I have tested the beta5 against Payara 4.1 (Glassfish 4.1) and TomEE-Plus 7.0.1.
The test code can be found here: https://github.com/mnesarco/mybatis-cdi-samples

Can you do some tests with WebLogic?

**Comment by mnesarco** [comment]
Hi @hazendaz @artplastika , What can we do with this issue?
- It refers to an old beta (beta2). 
- The current beta7 has been tested with Glassfish, Tomee, Websphere, Wildfly
- We have no WebLogic Environment to try to reproduce this.
- We do not support CDI 1.0, does WebLogic 12c support CDI 1.1 o 1.2 ?

**Comment by artplastika** [comment]
Hi @mnesarco I'll take a look on it next week. Thanks.

**Comment by mnesarco** [comment]
Hi @artplastika , have you had any time to check this?

**Comment by mnesarco** [comment]
Hi @hazendaz @artplastika 
Ok guys, I have tested this by myself on Oracle WebLogic 12c. It worked out of the box.

- Test App: https://github.com/mnesarco/mybatis-cdi-samples/
- Oracle WbLogic 12c installed: fmw_12.2.1.2.0_wls_quick 
- mybatis-cdi version: beta7
